### ISSUE TITLE
Clicking on a Type redirect redirects to home page

### ISSUE THREAD

**Issue by BannerBomb** [discordjs/docs#12]
For example clicking this "BaseImageURLOptions" will redirect to https://discord.js.org/docs/packages/rest/stable/BaseImageURLOptions:Interface#/ but instead of showing the type of data that can be passed it just shows the Docs home page as shown in the second image. All the properties with clickable "types" do this.
![image](https://github.com/discordjs/docs/assets/11788894/33284af2-6749-4949-be75-a1ad3c127f8f)
![image](https://github.com/discordjs/docs/assets/11788894/9c61513a-08b5-4436-ae11-4759bcea908c)

**Comment by sdanialraza** [comment]
That link works just fine for me, try clearing your cache

**Comment by BannerBomb** [comment]
> That link works just fine for me, try clearing your cache

ok. that worked, sorry. I guess my computer still had the old docs cached in it.
